{% set name = "parsnip-cif" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/glotzerlab/parsnip/archive/v{{ version }}.tar.gz
  sha256: da2131a45158d2e26120e091d3ecd8a25f822210b363a2527d1b3838e190d6ae

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.19
    - more-itertools

test:
  imports:
    - parsnip
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/glotzerlab/parsnip
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "Minimal library for parsing CIF & mmCIF files in Python."
  doc_url: http://parsnip-cif.readthedocs.io/
  dev_url: https://github.com/glotzerlab/parsnip

extra:
  recipe-maintainers:
    - janbridley
    - joaander
